### ISSUE TITLE
Extrinsic hash is None for unsigned extrinsic

### ISSUE THREAD

**Issue by hemz10** [polkascan/py-scale-codec#113]
I am trying to decode extrinsic for a block using `get_block` method from py-substrate interface. For an extrinsic with no signer, extrinsic hash is none.  How do we get extrinsic hash when there is no signer. 

Extrinsic hash is assigned to None [here](https://github.com/polkascan/py-scale-codec/blob/045b34813727f25602c2e5d2440fffc621d55680/scalecodec/types.py#L2890) when there is no signer 

Here is my code example:
```python
from substrateinterface import SubstrateInterface
def polkadot_decodeExtrinsic(self):
    substrate = SubstrateInterface(url="https://rpc.polkadot.io")
    block = substrate.get_block(
        block_hash='0xa25f3b3840989455423acd6626ceb9dc91b9d2044ee8430f234f8c0c46ed728c')
        for i, extrinsic in enumerate(block['extrinsics']):
                assert (extrinsic.value["extrinsic_hash"]) is None
               # This should not be none

```

Expected Behaviour:
The Hash should not be `None` and there should be some value as seen in [polkascan explorer](https://explorer.polkascan.io/polkadot/extrinsic/17256440-0) for the first and as well as second extrinsic.

Reference:
The same issue was reported. Issue link fyr [here](https://github.com/polkascan/py-scale-codec/issues/69)

**Comment by arjanz** [comment]
Included in release: https://github.com/polkascan/py-scale-codec/releases/tag/v1.2.7

**Comment by hemz10** [comment]
Thank you, It's working now !!
