### ISSUE TITLE
StakingLedger is outdated

### ISSUE THREAD

**Issue by kianenigma** [polkascan/py-scale-codec#21]
both polkadot and kusama have moved to `Vec<EraIndex>` for `claimedRewards` fields but seemingly the default presets have not been updated here. 

I wasn't sure how to update the json files, for anyone who has the same issue this is a fix:

```python
substrate = SubstrateInterface(
    url="ws://localhost:9944",
    address_type=0,
    type_registry={'types': {
            "StakingLedger<AccountId, BalanceOf>": {
                "type": "struct",
                "type_mapping": [
                    ["stash", "AccountId"],
                    ["total", "Compact<Balance>"],
                    ["active", "Compact<Balance>"],
                    ["unlocking", "Vec<UnlockChunk<Balance>>"],
                    ["claimedReward", "Vec<EraIndex>"]
                ]
            },
        }
    },
    type_registry_preset='polkadot',
)
```

**Comment by arjanz** [comment]
There was indeed a duplicate entry for `StakingLedger`, which I fixed in https://github.com/polkascan/py-scale-codec/commit/a2605de9756e22cb6539e1ec35f10fd060db47b6 (release v0.10.9). Also I've added the latest type registry updates for Kusama (2019) and Polkadot (17). Thanks for reporting!
