### ISSUE TITLE
Packaging with pyinstaller does not include the json metadata

### ISSUE THREAD

**Issue by LefterisJP** [polkascan/py-scale-codec#25]
Hey guys,

This is Lefteris from rotki. We use `py-substrate-interface` in rotki. Rotki generates a binary with the use of pyinstaller. Our latest release included the first version of kusama balance queries but we hit an unexpected bug: https://github.com/rotki/rotki/issues/2116

The bug only happens in packaged mode and not in normal develop mode. This quickly lead to figuring out that pyinstaller does not have a proper hook to include the py-scale-codec metadata when packaging. By metadata I am referring to all the json files.

We added a hook in our project as the [fix](https://github.com/rotki/rotki/pull/2118) of the problem in [this](https://github.com/rotki/rotki/pull/2118/commits/b7c2bd93fd2bf1d82f09e25c65ce40153eb019ea) commit.

The reason I am making this issue is that the way pyinstaller works the downstream projects should not have to add hooks for the packages they use. Instead the upstream projects, in this case py-scale-codec should provide the pyinstaller hook. This way all projects using it don't need to deal with anything.

There is documentation on how to do it here: https://pyinstaller.readthedocs.io/en/stable/hooks.html#provide-hooks-with-package

**Comment by arjanz** [comment]
Hi Lefteris, I haven't used PyInstaller before but sounds promising when making standalone applications. Is it possible to make a pull request here? Then it would be easier for us to review and merge the changes necessary. (And you'll be on the contributors list as a bonus ;)
