### ISSUE TITLE
Dublicated type definition

### ISSUE THREAD

**Issue by valentunn** [polkascan/py-scale-codec#31]
Hi, I noticed, that type `ParachainsInherentData` is defined twice in `default.json`: 
[first](https://github.com/polkascan/py-scale-codec/blob/master/scalecodec/type_registry/default.json#L1024)
[second](https://github.com/polkascan/py-scale-codec/blob/master/scalecodec/type_registry/default.json#L1045)

**Comment by arjanz** [comment]
That was indeed incorrect, thanks for pointing this out
