### ISSUE TITLE
More dublicated keys :)

### ISSUE THREAD

**Issue by valentunn** [polkascan/py-scale-codec#33]
Hi again! Thanks for your very quick response on the previous issue.

I found several other dublications:
DisputeStatementSet
MultiDisputeStatementSet
DisputeStatement
ValidDisputeStatementKind
InvalidDisputeStatementKind
ExplicitDisputeStatement
GlobalValidationData

**Comment by arjanz** [comment]
Hm seems like a recent merge went rogue.. I'll check the whole thing, thanks

**Comment by valentunn** [comment]
Thank you!
