### ISSUE TITLE
Adopt for the new runtime

### ISSUE THREAD

**Issue by valentunn** [polkascan/py-scale-codec#34]
Hi again, it seems like Westend runtime was updated to version 50, which brought some API-breaking changes.  For example, they finally migrated AccountInfo to TripleRefCount

**Comment by arjanz** [comment]
Yes I am aware of that, I am examining the recent and upcoming changes atm of Polkadot, Kusama, Rococo, Westend etc. Expect fixes for this later today.. Lots of changes incoming :)

**Comment by valentunn** [comment]
Thanks a lot)
