### ISSUE TITLE
New field in election_provider_multi_phase::Phase

### ISSUE THREAD

**Issue by valentunn** [polkascan/py-scale-codec#41]
Hi, there is a new field in election_provider_multi_phase::Phase called Emergency, which is not yet reflected in `default.json`:
https://github.com/paritytech/substrate/blob/6242d37f43ec5aa9b6131a8e61b8d4e71b063907/frame/election-provider-multi-phase/src/lib.rs#L337

This is already live on at least Westend

**Comment by arjanz** [comment]
You are right, thanks for reporting
