### ISSUE TITLE
Decoding "AccountInfo<Index, AccountData>

### ISSUE THREAD

**Issue by song-python** [polkascan/py-scale-codec#44]
Hello!
Why could this issue appear? I forked the substrate interface, and I am running into this:
scalecodec.exceptions.RemainingScaleBytesNotEmptyException: Decoding "AccountInfo<Index, AccountData>" - Current offset: 69 / length: 80

**Comment by arjanz** [comment]
Then the `AccountInfo` type definition specified in the type registry probably doesn't match the one in your node. 

You can try the options mentioned here: https://github.com/polkascan/py-scale-codec/issues/42#issuecomment-881383000

**Comment by song-python** [comment]
thanks
