### ISSUE TITLE
V14 Metadata decoder?

### ISSUE THREAD

**Issue by Polsaker** [polkascan/py-scale-codec#45]
Any news on the implementation of a v14 metadata decoder? I've got a couple implementations that are already breaking down due to

```
  File "substrateinterface/base.py", line 801, in get_block_metadata
    metadata_decoder.decode()
  File "scalecodec/base.py", line 434, in decode
    self.value = self.process()
  File "scalecodec/metadata.py", line 35, in process
    self.version = self.process_type('Enum', value_list=[
  File "scalecodec/base.py", line 497, in process_type
    obj.decode(check_remaining=False)
  File "scalecodec/base.py", line 434, in decode
    self.value = self.process()
  File "scalecodec/types.py", line 969, in process
    raise ValueError("Index '{}' not present in Enum value list".format(self.index))
ValueError: Index '14' not present in Enum value list
```

**Comment by arjanz** [comment]
Yes a lot of work has been done already, this is the feature branch that will be merged: https://github.com/polkascan/py-scale-codec/tree/feature/scale_info

There is also a release candidate already that contains V14: https://pypi.org/project/substrate-interface/1.0.0a2/

I expect to merge it to master by the end of this week, I have to update it with latest master. Note that there will be some breaking changes with the current `0.13.x` releases..

**Comment by Yxiaoyang** [comment]
sorry，i have a question,  i want connect a substrate chain, but I only have the official types.json, i want know can it work in python？ or tell me, what should I do

**Comment by arjanz** [comment]
Support for `MetadataV14` released in https://github.com/polkascan/py-scale-codec/releases/tag/v1.0.1 and https://github.com/polkascan/py-substrate-interface/releases/tag/v1.0.0

**Comment by arjanz** [comment]
Please note that this major release is not fully backwards compatible with the v0.11 releases
