### ISSUE TITLE
Kusama type registry needs update

### ISSUE THREAD

**Issue by JacquesBermanWebster** [polkascan/py-scale-codec#49]
Hello. I believe kusama type registry lacks some new data. I'm trying to get block #9438247 (for example) and get an error.
```
from substrateinterface import SubstrateInterface
substrate = SubstrateInterface(
    url='wss://kusama-rpc.polkadot.io',
    ss58_format=2,
    type_registry_preset='kusama',
)
block = substrate.get_block(block_number=9438247)

Traceback (most recent call last):
  File "/home/substrate/venv/lib/python3.8/site-packages/scalecodec/types.py", line 1024, in process
    enum_type_mapping = self.type_mapping[self.index]
IndexError: list index out of range
```
I believe kusama's type registry lacks new data from here (https://github.com/polkadot-js/api/blob/master/packages/types-known/src/spec/kusama.ts#L194).
For example, if I add following types to kusama type registry, everything goes well and I get desired block:
```
"MultiLocation": "MultiLocationV0",
"MultiAsset": "MultiAssetV0"
```

**Comment by arjanz** [comment]
You were spot on, thanks for reporting again! I will include this in next upcoming release
