### ISSUE TITLE
Extrinsics of type staking(chill) are not decoded

### ISSUE THREAD

**Issue by pavelrib** [polkascan/py-scale-codec#56]
For any of the extrinsics here - https://polkadot.subscan.io/extrinsic?module=staking&call=chill.

**Comment by pavelrib** [comment]
Yes, I've tried. Those extrinsic are returned as None (as I've set decoding errors handling).

**Comment by arjanz** [comment]
Fix released in https://github.com/polkascan/py-scale-codec/releases/tag/v1.0.10
