### ISSUE TITLE
Decoder class for "DispatchInfo" not found

### ISSUE THREAD

**Issue by freddieee** [polkascan/py-scale-codec#6]
Raising this error when trying to decode the event data;
`Decoder class for "DispatchInfo" not found`

**Comment by emielvanderhoek** [comment]
Resolves to lover level decoder classes: https://github.com/polkascan/py-scale-codec/blob/afd1a8f371fa65a42f7f7d832a208ce916dbb850/scalecodec/type_registry/default.json#L61
