### ISSUE TITLE
No Type Registry for Karura Network

### ISSUE THREAD

**Issue by DanielMS93** [polkascan/py-scale-codec#61]
I am trying to use the py-substrate-interface module for interfacing with the Karura network.

I am unsure however how to create a type registry json that is set up in scale codes format.

Does anyone know how to find this type registry for Karura or how to generate from somewhere?

**Comment by arjanz** [comment]
This would be very specific to the required structure of the call params of this call.. What you can try is to decode an existing extrinsic containing this call and diff to check what you are missing

**Comment by arjanz** [comment]
But I agree some better debug message or more context could be provided, I'll look into that in the near future

**Comment by arjanz** [comment]
> is this possible with the py substrate api?

If all the data is available on-chain in storage function, this should be possible..

A type registry for Karura is now included in the lastest version of scalecodec btw
