### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get' running binary compiled via pyinstaller

### ISSUE THREAD

**Issue by mmvds** [polkascan/py-scale-codec#67]
I've compiled my project, it uses only the following imports:
before that I've updated substrate-interface with all the dependencies
```
import requests
import time
import sys
from substrateinterface import SubstrateInterface, Keypair
```
successfully compiled standalone via 
pyinstaller -F ./dutch.py
when I run the binary file on the same machine, I'm getting the following error:

```
Traceback (most recent call last):
  File "dutch.py", line 239, in <module>
    substrate = init_network_params(is_prod)
  File "dutch.py", line 36, in init_network_params
    substrate = SubstrateInterface(
  File "substrateinterface/base.py", line 479, in __init__
  File "substrateinterface/base.py", line 2919, in reload_type_registry
  File "scalecodec/base.py", line 254, in update_type_registry
AttributeError: 'NoneType' object has no attribute 'get'
[465234] Failed to execute script 'dutch' due to unhandled exception!
```
init_network_params(is_prod) function:
```
def init_network_params(is_prod):
    if is_prod:
        wss_url = "wss://kusama-rpc.polkadot.io/"
    else:
        wss_url = "wss://127.0.0.1/"
    substrate = SubstrateInterface(
        url=wss_url,
        ss58_format=2
    )
    return substrate
```
Do you have any proposals how to solve this, or maybe best practices how to make a wheel or binary, included scalecodec -> substrate-interface?
p.s. I've also checked with Nuitka project and got the same error for binary file

**Comment by arjanz** [comment]
Or does this only occur when you compile it to a binary? I have to say that I have no experience with pyinstaller
