### ISSUE TITLE
Updating Crust network `type_registry`

### ISSUE THREAD

**Issue by PaTara43** [polkascan/py-scale-codec#75]
Hi!

There is a `type_registry` update in Crust network!

- Current in py-scale-codec: [`FileInfo`](https://github.com/polkascan/py-scale-codec/blob/master/scalecodec/type_registry/crust.json#L46).

- Actual in Crust: [`FileInfoV2`](https://github.com/crustio/crust.js/blob/mainnet/packages/type-definitions/src/market.ts#L14).

Same for `Replica`.

- [Current](https://github.com/polkascan/py-scale-codec/blob/master/scalecodec/type_registry/crust.json#L69) in py-scale-codec.

- [Actual](https://github.com/crustio/crust.js/blob/mainnet/packages/type-definitions/src/market.ts#L25) in Crust.

**Comment by arjanz** [comment]
Updated the type registry according to types defined at: https://github.com/crustio/crust.js/blob/5f20ee179b98cc378efb06b1e55c282c735a72c9/packages/type-definitions/src/json/types.json

**Comment by PaTara43** [comment]
Would you kindly update the https://github.com/polkascan/py-substrate-interface with the new template?

**Comment by arjanz** [comment]
> Would you kindly update the https://github.com/polkascan/py-substrate-interface with the new template?

I will release this soon, for the time being you can update: `pip install scalecodec==1.0.39`

**Comment by PaTara43** [comment]
Well, yes, but the substrate-interface uses 1.0.37

**Comment by arjanz** [comment]
> Well, yes, but the substrate-interface uses 1.0.37

`scalecodec>=1.0.37,<2` to be exact, so installing from scratch will install the newest and if you specify it explicitly in your requirements file it wouldn't be a version conflict..  But don't worry, there is a release planned today

**Comment by PaTara43** [comment]
Sorry, didn't notice that. Thanks!

**Comment by arjanz** [comment]
Released in: https://github.com/polkascan/py-substrate-interface/releases/tag/v1.2.8
